### ISSUE TITLE
http://www.rapydscript.com/discussions/ does not work in FF 37, works in i.e. 11

### ISSUE THREAD

**Issue by jnowl** [atsepkov/RapydScript#59] opened 2015-05-15 17:37 UTC

**Comment by atsepkov** [comment] 2015-05-30 18:10
Thanks, noted. Looks like the problem is with the plugin I'm using for embedding google hangouts (I wish hangouts had an API for retrieving posts). Closing because the issues here are for the language itself rather than the website.

**Closed by atsepkov** 2015-05-30 18:10 UTC
