### ISSUE TITLE
REPL : Forgot to include "var" ?

### ISSUE THREAD

**Issue by mardon86** [atsepkov/RapydScript#107] opened 2015-11-12 02:13 UTC
>>> a = [1,2,3,4,5]
---------- Compilation ---------
a = [ 1, 2, 3, 4, 5 ];
---------- Execution ---------
ReferenceError: a is not defined
    at <repl>:1:16
    at Object.exports.runInContext (vm.js:44:17)
    at runjs (/home/DATA/GITs/RapydScript/tools/repl.js:293:25)
    at compile_source (/home/DATA/GITs/RapydScript/tools/repl.js:352:9)
    at push (/home/DATA/GITs/RapydScript/tools/repl.js:363:26)
    at Interface.<anonymous> (/home/DATA/GITs/RapydScript/tools/repl.js:380:20)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface._line (readline.js:549:8)
>>> a
---------- Compilation ---------
a;
---------- Execution ---------
[ 1, 2, 3, 4, 5 ]
>>> for i in a:
...     print(i)
... 
... 
---------- Compilation ---------
var ՐՏ_Iter1 = ՐՏ_Iterable(a);
for (var ՐՏ_Index1 = 0; ՐՏ_Index1 < ՐՏ_Iter1.length; ՐՏ_Index1++) {
    i = ՐՏ_Iter1[ՐՏ_Index1];
    ՐՏ_print(i);
}
---------- Execution ---------
ReferenceError: i is not defined
    at <repl>:3:7
    at Object.exports.runInContext (vm.js:44:17)
    at runjs (/home/DATA/GITs/RapydScript/tools/repl.js:293:25)
    at compile_source (/home/DATA/GITs/RapydScript/tools/repl.js:352:9)
    at push (/home/DATA/GITs/RapydScript/tools/repl.js:363:26)
    at Interface.<anonymous> (/home/DATA/GITs/RapydScript/tools/repl.js:375:24)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface._line (readline.js:549:8)

**Comment by atsepkov** [comment] 2015-11-12 05:11
Could you share more information on your environment, use case and what you're doing, as well as which version you're using? From the output you've posted, I'm assuming you're using REPL? However, when I run the same command it works fine for me:

    ▶ rapydscript
    Welcome to the RapydScript REPL! Press Ctrl+C twice or use quit() to quit.
    You can use the `repl` object to check/modify settings specific to this prompt.
    Use repl.showJavascript=True to stop the REPL from showing the compiled JavaScript.
    
    >>> a = [1,2,3,4,5]
    ---------- Compilation ---------
    a = [ 1, 2, 3, 4, 5 ];
    ---------- Execution ---------
    [ 1, 2, 3, 4, 5 ]
    >>> a
    ---------- Compilation ---------
    a;
    ---------- Execution ---------
    [ 1, 2, 3, 4, 5 ]
    >>> for i in a:
    ...     print(i)
    ...
    ...
    ---------- Compilation ---------
    var ՐՏ_Iter0 = ՐՏ_Iterable(a);
    for (var ՐՏ_Index0 = 0; ՐՏ_Index0 < ՐՏ_Iter0.length; ՐՏ_Index0++) {
        i = ՐՏ_Iter0[ՐՏ_Index0];
        ՐՏ_print(i);
    }
    ---------- Execution ---------
    1
    2
    3
    4
    5
    undefined
    >>> quit()
    ---------- Compilation ---------
    quit();
    ---------- Execution ---------
    ▶

**Comment by mardon86** [comment] 2015-11-12 05:44
Thanks for your quick respond. I'm using the git version, then I create a symbolic link in /usr/bin pointing to Rapydscript/bin/rapydscript. Am I missing something ?

**Comment by mardon86** [comment] 2015-11-12 05:51
Yes, I'm using repl. Run rapydscript without arguments, then simply type the code,,

**Comment by atsepkov** [comment] 2015-11-12 06:38
Interesting, as you noted, the issue has the symptoms of missing "var" keyword somewhere, and I'm not sure why it's occurring for you, could you double-check that you're using the latest version (rapydscript -V)? Also, what version of node?

The REPL does indeed process input slightly differently than the compilation. The output is executed in a sandbox (https://nodejs.org/api/vm.html) that doesn't have access to local environment. Hence the 'var' isn't declared the same way as it would be in execution. Additionally, strict mode always requires a declaration, so if I remember correctly, RS appends these variables to global object rather than 'var'ing them in REPL, but I could be wrong and will not be able to double-check that until later in the week. That still doesn't explain why you're seeing an issue when the variables work fine in my own testing.

**Comment by kovidgoyal** [comment] 2015-11-12 07:13
https://github.com/kovidgoyal/rapydscript-ng/commit/724d786e9995a5f023e6e5d983eba87b583f2747

@atsepkov This has nothing to do sandboxing. The REPL uses the compilers --bare mode which uses display_body() instead of display_complex_body() which therefore does not output variable declarations. I dont know why that was done? An optimization perhaps?

**Comment by atsepkov** [comment] 2015-11-12 07:53
@kovidgoyal Ok, I was under the impression that this was due to REPL's VM. Your version also didn't use the "strict" mode in REPL when I merged it, and this error is triggered by strict mode, have you added it in since then? I'm also still confused why I'm not experiencing this 'var' error in my own REPL.

As for `display_complex_body`, the reason bare mode doesn't use it is because that function was designed for functions and classes - if AST_TopLevel in bare mode works with it correctly it's purely by coincidence, not by design.

**Comment by kovidgoyal** [comment] 2015-11-12 08:03
I doubt it is possible to use strict mode in the REPL. IIRC webkit ignores "use strict" at the global scope. In order to trigger strict mode in the REPL you would probably have to run node with a command line arg or env var to turn it on, like `node --use_strict` which is probably what the OP is doing. 

Note that in non-bare mode, display_complex_body() is used for AST_Toplevel rather than display_body(). So I find it odd that it is not used in bare mode.

**Comment by atsepkov** [comment] 2015-11-12 08:38
I don't use `bare` often, so I didn't test it well. I don't remember my justification for updating AST_TopLevel to `display_complex_body`, but it was probably similar to what I explained above (since it shares AST_Scope parent), additionally AST_TopLevel is actually rendered inside a self-executing function when not in `bare` mode - so it seemed relatively safe to do, although in all honesty I don't remember doing it (it's the interactions with arguments and decorators that make `display_complex_body` more dangerous without a function wrapper). If it works correctly without function wrapper and no weird use case will trigger it dumping some logic that reads "arguments", I have no problem with updating it. As far as using strict in REPL, it is possible, here is the hack I used:

    result = vm.runInContext('"use strict";' + js, ctx, {'filename': '<repl>', 'displayErrors': false});

I have to pass that with every call to vm, but it works as expected - hence the sandboxing comment I made earlier - because I see no other reason why "use strict" directive would need to be passed with every call. I also tried `node --use_strict`, that had no effect inside `vm`.

**Comment by kovidgoyal** [comment] 2015-11-12 08:46
Well, all display_complex_body does for AST_Toplevel is call declare_vars(0 and display_body() so perhaps the correct fix is to change both places to display_body()

But does you strict hack actually work? i.e. does v8 interpret the javascript in strict mode?

**Comment by atsepkov** [comment] 2015-11-12 08:50
Yea, until I added it, statements like this would produce "undefined", now it's an error:

    >>> b = a
    ---------- Compilation ---------
    b = a;
    ---------- Execution ---------
    ReferenceError: a is not defined
    at <repl>:1:18
    at Object.exports.runInContext (vm.js:64:17)
    at runjs (/Users/alexander.tsepkov/work/RapydScript/tools/repl.js:293:25)
    at compile_source (/Users/alexander.tsepkov/work/RapydScript/tools/repl.js:352:9)
    at push (/Users/alexander.tsepkov/work/RapydScript/tools/repl.js:363:26)
    at Interface.<anonymous> (/Users/alexander.tsepkov/work/RapydScript/tools/repl.js:380:20)
    at Interface.emit (events.js:107:17)
    at Interface._onLine (readline.js:214:10)
    at Interface._line (readline.js:553:8)
    at Interface._ttyWrite (readline.js:830:14)
    >>>

**Comment by kovidgoyal** [comment] 2015-11-12 08:58
Interesting, but it is not quite the same as strict mode. As per the spec, strict mode should return referenceerrors for any undeclared variable that does not exist on the global object, even when used on the LHS of an assignment, which it does not. So it looks like it is some kind of pseudo-strict mode. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Converting_mistakes_into_errors

The OP on the other hand seems to have somehow achieved the full strict mode in his instance of node. So as I said earlier he is either using some env var that triggers that behavior or a custom version of v8

**Comment by kovidgoyal** [comment] 2015-11-12 09:41
Also I will note that in my fork, a = b gives a ReferenceError even without that hack. I think the reason you need the hack is that you have an extra semi-colon after use strict at the top of tools/repl.js That makes the use strict declaration be ignored. This is likely a bug you inherited when you copied the code from my fork :)

**Comment by mardon86** [comment] 2015-11-12 12:05
I have re-cloned the git and got the same result. (rapydscript-0.3.9, nodejs-4.2.1)

**Comment by mardon86** [comment] 2015-11-12 12:35
Installing rapydscript via npm, then upgrading node to 5.0.0 also got the same result

**Comment by kovidgoyal** [comment] 2015-11-12 12:36
The fix is in my fork of rapydscript, rapydscript-ng not in this fork. If you want to try it, you have to switch to that.

**Comment by mardon86** [comment] 2015-11-12 12:47
Ok, i'll try rapydscript-ng. @atsepkov @kovidgoyal  thanks for your time..

**Comment by atsepkov** [comment] 2015-11-12 13:13
@mardon86 out of curiosity, are you able to try with node 0.12? I wonder if 4.2.1 defaults to strict mode.

**Comment by mardon86** [comment] 2015-11-12 13:24
Strange.. It works on node-0.12.7 !

**Comment by atsepkov** [comment] 2015-11-12 13:37
Not strange, it all makes sense now. node 4.2.1+ uses strict mode by default.

**Comment by mardon86** [comment] 2015-11-12 15:55
Ok, thx.

**Closed** 2015-11-16 14:45 UTC

**Comment by cjrh** [comment] 2016-07-23 04:37
I'm getting the same problem. 

```
Welcome to the RapydScript REPL! Press Ctrl+C twice or use quit() to quit.
You can use the `repl` object to check/modify settings specific to this prompt.
Use repl.showJavascript=True to stop the REPL from showing the compiled JavaScript.

>>> for i in range(10):
...     print(i)
...
...
---------- Compilation ---------
for (i = 0; i < 10; i++) {
    ՐՏ_print(i);
}
---------- Execution ---------
ReferenceError: i is not defined
    at <repl>:1:21
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Object.exports.runInContext (vm.js:67:17)
    at runjs (/usr/local/lib/node_modules/rapydscript/tools/repl.js:293:25)
    at compile_source (/usr/local/lib/node_modules/rapydscript/tools/repl.js:352:9)
    at push (/usr/local/lib/node_modules/rapydscript/tools/repl.js:363:26)
    at Interface.<anonymous> (/usr/local/lib/node_modules/rapydscript/tools/repl.js:375:24)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
>>> quit()
---------- Compilation ---------
quit();
---------- Execution ---------

$ rapydscript -V
rapydscript 0.3.9
$ node --version
v6.3.1
```

Is there something I should be doing differently, or setting an option?
