### ISSUE TITLE
RS happily compiles user input that violates strict mode without raising an error

### ISSUE THREAD

**Issue by kovidgoyal** [atsepkov/RapydScript#69] opened 2015-06-23 08:34 UTC
The compiler outputs function definitions that are not at the top-level in strict mode.

```
echo 'if True:\n   def f():\n      pass' | rapydscript -p
(function(){
    "use strict";
    var _$rapyd$_Temp;
    if (true) {
        function f() {
        }
    }
})();
```

This is not allowed. Either the compiler should not be using strict mode, or it should raise a SyntaxError. Otherwise the javascript engine will raise a syntax error for this code at runtime, which is sub-optimal.

**Comment by kovidgoyal** [comment] 2015-06-23 08:36
Forgot to add:

This is the error message from Node for this invalid javascript:
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.

**Comment by atsepkov** [comment] 2015-06-23 13:22
Good catch. I do want to reemphasize, however, the message thrown by node. The problem is not that the function is not declared at top level, the problem is that it's declared within a conditional. This in itself is an anti-pattern, which RapydScript does not currently catch.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Paving_the_way_for_future_ECMAScript_versions

**Comment by kovidgoyal** [comment] 2015-06-23 13:41
The easy solution is to detect it and raise an error at compile time. The not so easy solution is to mangle the function name and define it at top level then assign it to a variable defined inside the if block.

This kind of pattern is pretty common in python, for example to define different versions of a function or class depending on the operating system.

**Comment by kovidgoyal** [comment] 2015-06-23 13:43
Actually, I think the not so easy solution is pretty hard. Because you have the problem of lifting the functions scope out of the conditional block as well.

**Comment by atsepkov** [comment] 2015-06-26 18:57
Personally, not a fan of this pattern. While there are debatably legitimate uses for it (like different implementations based on current environment), the equally easy (yet dangerous) pattern of switching the function definition on the fly is an easy way to shoot oneself in the foot by introducing inconsistent behavior. A similar, but better approach, in my opinion is defining separate objects with a shared interface (i.e. Windows and Linux classes that both inherit from OS and override OS-specific methods). The difference is that in one case you're conditionally defining a function (bad), in another you're simply performing conditional assignment/call (ok).

In fact, `strict` JavaScript will have no problem with you performing conditional assignment to achieve the same result either:

    # bad
    if conditional:
        def a(): ...

    # ok
    if conditional:
        a = def(): ...

Python doesn't have the benefit of anonymous functions (aside from the more-limited lambdas), so we don't see that pattern there.

**Comment by kovidgoyal** [comment] 2015-06-27 01:45
I dont much care what is done about this, either have the compiler auto fix or have it bail with an error. But it *must* do *something*, not silently generate invalid code, that will only be discovered at runtime.

I suspect that this problem is more general, you'd also want to detect functions being defined inside loops, switch statements (although I cant recall if RS ever generates switch statements.

**Comment by hartsantler** [comment] 2015-06-27 16:16
whats the point of `strict mode` when its really just designed for producing better errors for debugging, and not performance.  It makes some sense with handwritten JS, but something coming out of a transpiler should have less issues like that.

http://stackoverflow.com/questions/3145966/is-strict-mode-more-performant

**Comment by atsepkov** [comment] 2015-06-27 16:59
The main motivator for adding strict mode to generated code is its handling of bad user data/logic. Python's mantra of asking for forgiveness rather than permission is completely useless in JavaScript world, which will happily perform non-sensical math operations, initialize a global you assigned to by mistake, ignore assignment to read-only property without raising an error, and so on.

Strict mode makes several of these silent warnings/errors into explicit errors/exceptions, allowing us to detect these problems sooner, as well as employ the familiar try/catch pattern more often.

I agree that the requested feature (having the compiler do its own pass to detect these errors before you run the code) would be nice. However, this is the case of garbage in, garbage out. A typical compiler for a dynamically typed language will only catch the most basic syntax errors at compile time, the rest are discovered at run time. The is not a silent failure that blows up in your face 1000 lines of code later, it's very easily discovered when you run your code (as you should do before deploying it), so I don't see an issue with delegating this error catching to strict mode itself. Having a linter for these cases be part of the compiler would be nice, but not the top priority. I'll leave this issue open but will update the title.

**Comment by kovidgoyal** [comment] 2015-06-30 03:33
Here's another instance of this class of bug:
```
echo 'def f(a, a):pass' | rs | node

SyntaxError: Strict mode function may not have duplicate parameter names
```

I have already fixed this as part of the work I am doing to get rid of the kwargs decorator and support both *args and **kwargs in function definitions natively, but I thought I'd mention it here in case you decide not to merge my work.

**Comment by kovidgoyal** [comment] 2015-07-03 12:56
FYI: I have added this functionality to the linter in my fork.

https://github.com/kovidgoyal/RapydScript/commit/f8b34ae02ab3ff303fbd9d6da769057be9aefce6

**Comment by kovidgoyal** [comment] 2015-07-04 08:16
Another bug of this type:

echo '{a:1, a:1}' | rs | node

SyntaxError: Duplicate data property in object literal not allowed in strict mode

**Closed** 2015-08-13 04:33 UTC
Labels: linter
