### ISSUE TITLE
comparing DOM-elements

### ISSUE THREAD

**Issue by valq7711** [atsepkov/RapydScript#135] opened 2016-12-11 19:44 UTC
Comparing operators (==, !=)  on objects that are DOM-elements  return incorrect result.
example:
`d1 = document.getElementById("d1")`
`d2 = document.getElementById("d2")`
`d1==d2  # = True!`

[bug_test.html.txt](https://github.com/atsepkov/RapydScript/files/644726/bug_test.html.txt) (see browser console)

**Comment by atsepkov** [comment] 2016-12-11 20:33
So DOM elements in general aren't well-suited to arithmetic operations, and `==` wouldn't be my operation of choice here, I recommend `d1.isEqualNode(d2)` or `d1.isSameNode(d2)` (these methods were created for this purpose), or at the very least `is`, which is equivalent to JS identity operator `===`. Based on that alone, I would conclude that this is not a bug.

However, before closing it I want to understand the behavior a bit more to make sure there are no other bugs lurking here. The attached text file only has the ids of the elements in it (d1, d2), but tells me nothing about what the 2 elements are. Are you comparing 2 unrelated nodes (i.e. a `div` and a `span`)? Are you comparing 2 nodes with equal content?

**Comment by valq7711** [comment] 2016-12-12 16:26
I caught this "bug" while comparing 2 tr-elements  with different context. OK, I'll  try  `isSameNode( )` or `is` - it's what I need, thank you!

**Closed** 2016-12-13 16:17 UTC
