### ISSUE TITLE
__call__ special method not working

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#98] opened 2015-09-19 02:55 UTC
#### Context
```
class tester:
  def __init__(self):
    print("init")

  def go(self):
    print("go")
    
# specal method:
  def __call__(self, arg):
    print("call:", arg)

test = tester()
test.go()
test.__call__(1)
test(2)                   # <<<< invoke the special method; use object as functor
```

#### Expected and Desired Behavior (ordinary python)

```
init
go
call: 1
call: 2
```
This works just fine in python2.7, python3.4, ipython2.7, and ipthon3.

#### Observed Behavior (RS)
```
init
go
call: 1
[stdin]:152
test(2);
^
TypeError: object is not a function
    at [stdin]:152:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at Socket.<anonymous> (node.js:164:11)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

#### Workaround
```
Just invoke test.__call__(...) instead of test(...)
```

#### Discussion

There are ways of making functors in javascript, using closures ... but I reckon it is both easier (at compile time) and more efficient (at run time) if the compiler just catches the pythonic functor expression and maps it to the ``__call__`` special method.

**Comment by kovidgoyal** [comment] 2015-09-19 03:05
There is no robust way to make this work. It suffers from the same issue as operator overloading. Namely, JavaScript has no support for it, which means either you overload all calls at the compiler level for a large performance hit or no calls, which leaves you with no way to implement it.

**Comment by hartsantler** [comment] 2015-09-19 04:33
@kovidgoyal it is possible to support in a robust way, and without much overhead, only in the constructor of the class is a little extra overhead when binding `__call__`, and doing a copy of the data in `this`.  See my hack here:
https://github.com/rusthon/Rusthon/commit/4bfb36006e43819bd00d2ad8280bd74b416a8388

**Comment by kovidgoyal** [comment] 2015-09-19 04:39
Using __proto__ is problematic, for two reasons:

1) __proto__ is not available in all JS runtimes
2) It changes the inheritance chain of the object, which is an unexpected side-effect for defining a __call__ method

**Comment by kovidgoyal** [comment] 2015-09-19 04:40
Oh and I forgot that it has very poor effects on performance, ssee the warning at the top of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

**Comment by hartsantler** [comment] 2015-09-19 04:42
if `__proto__` is not available, you can loop over all the functions bound to myclass.prototype, and rebind those methods to the function/object `__call__` that the constructor returns.
its true there is some overhead at construction time, but not when normally calling methods on the instance.

**Comment by kovidgoyal** [comment] 2015-09-19 04:49
Not quite. Messing with __proto__ (and for that matter inserting another object into the prototype chain), slows down *all* attribute access on that object. see the MDN page I linked to earlier.

**Comment by hartsantler** [comment] 2015-09-19 05:11
A function object has `__proto__` defined as an empty object, so in giving it the prototype of the class, is not going to slow things down in any noticeable way.  That is what is being returned, and having its `__proto__` changed, not the original class or `this` instance.

**Comment by kovidgoyal** [comment] 2015-09-19 05:21
So you are saying MDN is wrong? If you want me to believe that, you are going to have to provide some benchmarks.

**Comment by hartsantler** [comment] 2015-09-19 05:36
The overhead is minimal, and i would suspect the V8 JIT can still optimize it just as well as a regular object.  Keep in mind the following:
* a function object has an empty `__proto__`, so assigning it to the class'es prototype will likely not require the JIT to throw away what it has cached so far, and simply resize the internal Function-struct to hold the extra field.
* the use of `__call__` is rare, and so is attaching data to Function objects.  Its unlikely the JIT will need to resize the Function-struct very often, if at all.
* the prototype of the original class, and class instance, are not touched, the inheritance chain remains the same.

**Comment by kovidgoyal** [comment] 2015-09-19 05:46
Again, I need benchmarks, speculating on how the internals of something as complex as a JIT works is not convincing, especially in the presence of explicit warnings from the makers of one of those JITs.

Yes the prototype of the original class is not touched, but the prototype of the object is, which means the **object's** inheritance chain is changed. However, I am willing to agree that that is an acceptable price to pay, since it only happens for objects created from classes that have __call__ defined.

**Comment by hartsantler** [comment] 2015-09-19 05:57
Again, i need to point out, the class is not touched, and the object `this` is not touched, its inheritance chain is not changed.  

The constructor returns a `function-object` instead of a regular `object`.  MDN is correct that changing the `__proto__` of a regular object is bad, on many levels.  However, this is a special case where a nested function, with an empty `__proto__` is given one, and returned.

**Comment by kovidgoyal** [comment] 2015-09-19 06:01
And you are assuming that dynamically changing an objects prototype has no performance impact as long as the original prototype is empty? I see absolutely no basis for that assumption. Maybe that assumption is correct, I dont know, I am saying, I need some benchmarks to prove that assumption.

**Comment by hartsantler** [comment] 2015-09-19 06:11
I am saying that: if the original prototype is empty, and not changed later, then the impact on the JIT is going to be almost nothing.  Why? because the `hidden-class` (created by the JIT) of the nested function that gets returned by the constructor; will not need to be resized, and so the hidden class should only be created once, and remain valid for the entire run of the JIT.

http://thibaultlaurens.github.io/javascript/2013/04/29/how-the-v8-engine-works/

**Comment by kovidgoyal** [comment] 2015-09-19 06:18
That argument would apply just as well to changing a non-empty prototype, and yet, you agree that changing a non-empty prototype is bad. If you change a prototype once (regardless of whether it is empty or not), the JIT can no longer assume that the prototype is unlikely to be changed again. That is almost certainly the cause of the performance problem. Anyway, this is getting nowhere, fast. The easiest way to win this argument is create a benchmark.

**Comment by hartsantler** [comment] 2015-09-19 06:32
Why can the JIT no longer assume that the prototype is unlikely to be changed again, because it was changed once?  One of the main things the JIT is doing is tracking hidden-classes, seeing which ones have been invalidated by fields who are deleted or when fields have changed type, and rebuilding them as required.  

At some point the JIT is likely to drop hidden-class optimization on some type and fall back to using a regular HashTable, but that is only going to happen after a field has been removed or changed its type many times.

**Comment by kovidgoyal** [comment] 2015-09-19 06:39
I am done with this -- what is it with you -- you just like arguing for the sake of arguing?

One final time: you want to convince me that changing the prototype has no performance side-effects on subsequent attribute access of the resulting object, you need to write a benchmark that demonstrates that.

**Comment by hartsantler** [comment] 2015-09-19 06:43
write the benchmark yourself punk.

**Comment by kovidgoyal** [comment] 2015-09-19 07:08
ROFL how did I just know that was coming.

**Comment by artyprog** [comment] 2015-09-19 08:01
If only I have your knowledges I would attempt to unify our competences to
accomplish great things
for the community.....
Life is very short, don't waste it....

2015-09-19 9:08 GMT+02:00 Kovid Goyal <notifications@github.com>:

**Comment by kovidgoyal** [comment] 2015-09-20 04:24
To summarize, the problems with using function objects to implement ```__call__``` are:

1) Changing object prototype dynamically is not available in all JS runtimes. This could potentially be worked around by manually copying properties, but IMO, that is just a slow, ugly mess.

2) The list of properties and type of the object will be changed by simply adding a ```__call__``` method to the object. This is highly unexpected. See code below:
```js
o = Object.create(null)
f = (function () {})
typeof o == 'object'
typeof f == 'function'
typeof o.apply == 'undefined'
typeof f.apply == 'function'

3) No evidence beyond vague hand-waving was presented to counter the claim on MDN that dynamically changing the prototype will slow down attribute access on the resulting object

1) I am willing to ignore this -- ``__call__`` simply wont work for runtimes without this facility.

2) This is a problem. In particular the type() of the resulting object changing is highly unexpected. Any code based on type inspection that expects an object will break.

3) This is a problem, unless someone can present some actual evidence that it is not.


IMO the call operator ```()``` suffers from the same problem as all other operators in RS -- namely that it cannot be overloaded. Any solution for this problem should be a general solution for the operator overloading problem as a whole. I am still inclined towards simply enabling all operator overloading on a per-module basis. This allows the user to choose which is more important to him -- performance or python compatibility, on a fairly granular level.

The issue with that is the different behavior of indexOf() when used with non-primitive types. I am inclining towards ignoring that as the cost of doing business. The RS provided index() method can be made to work (it will check if the passed in argument has an ``__eq__`` method, and if it does it will loop through the array checking with ``__eq__`` and otherwise fallback to indexOf). This should cover 99% of the use cases. It is still not fully compatible with python since in theory, a custom class could has an ``__eq__`` method that returns true for primitive types, but that should be pretty rare.

There is a similar issue with the python-like dict and set types. Currently in my fork I have an implementation for them that use the JS Map and Set types where available. The problem with that is that they do not use ``__hash__`` and ``__eq__``. This can be worked around by implementing a
hashmap in pure JS that will use those methods when defined, otherwise falling back to toString().

**Closed** 2016-08-31 06:26 UTC
