### ISSUE TITLE
more destructuring : (1,2) == (1,2)  fails

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#91] opened 2015-09-14 16:30 UTC
#### Context
```
# #! /usr/bin/python
x, y   = [123, 'x'] ; print("123, x --> ",   x, y)
[x, y] = [456, 'x'] ; print("[456, x] --> ", x, y)
#(x, y) = [789, 'x'] ; print("(x,y)", x, y)
print("()==() --> ", (1,2) == (1,2))
print("[]==[] --> ", [1,2] == [1,2])
```
#### Expected and Desired Behavior (standard python)
123, x -->  123 x
[456, x] -->  456 x
()==() -->  True
[]==[] -->  True

#### Observed Behavior
```
123, x -->  123 x
[456, x] -->  456 x
()==() -->  False
[]==[] -->  False
```

The -ng fork behaves the same.

**Comment by atsepkov** [comment] 2015-09-14 17:13
@JohnDenker the equality is not a bug. I think you're misunderstanding the difference between Python and JavaScript. This is exactly why I make the disclaimer that RapydScript is not Python. In Python, the `==` is a deep equality operator. In JavaScript the `==` is... a crap operator (it acts like identity operator for `object`s and lax equality for primitives). Luckily there is also a `===` operator, which is more consistent in that it tests identity/strict equality for both, this is what RapydScript `==` operator compiles to, it's a middle ground between Python's `is` and `==`.

RapydScript also comes with a version of deep equality, a function called `eq()`. The operation you want is `eq([], [])`. Compiling `==` to `eq()` automatically, unfortunately, is not feasible at this time. The main goal of RapydScript (and what makes it better than Skulpt, Pyjamas, Brython, or other frameworks that try to **be** Python) has always been performance. The overhead of a function call is enormous. Here are two examples, feel free to repeat them yourself in a REPL:

    def a(t):
        s = Date.now()
        for i in range(t): 1 == 1
        print(Date.now()-s)

    def b(t):
        s = Date.now()
        for i in range(t): eq(1, 1)
        print(Date.now()-s)

    a(1e7) # 17ms
    b(1e7) # 110-140 times slower

**Comment by atsepkov** [comment] 2016-08-31 06:43
Duplicate of #93 , see http://blog.pyjeon.com/2015/12/07/equality-operator/ , to summarize, add the following line at the top of your code and you'll have blazing fast deep equality:

    from danger_zone import equality

Unless I see problems with it, this will eventually be the default.

**Closed by atsepkov** 2016-08-31 06:43 UTC
