### ISSUE TITLE
preliminary benchmarking

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#94] opened 2015-09-16 03:29 UTC
> I suggest you do some benchmarking for yourself, you are not going to be convinced otherwise. And if you discover a technique by which you can replace == with something that has python like semantics for only a few % slowdown, I will be delighted to implement it.

That is an excellent suggestion.  It's good to have fact-based discussions.  I have accepted the suggestion ... and thereby hangs a tale.  Once upon a time a really, really smart programmer warned me never to guess about what needs optimizing and what doesn't.
* Such things are difficult to measure reliably.
* If it's hard to measure, it's a 100 times harder to guess.
* Moderately careful experiments suffice to tell you how hard the problem is.  They suffice to tell you that the results are wildly sensitive to details.

Here are three sets of results -- from running the same code on three different platforms -- followed by some discussion.

```
"0: time ;1!=0     0 ns  10 ps" 
"1: time +(1!=0)   0 ns  10 ps" 
"2: time +(x!=y++) 1 ns  1023 ps" 
"3: time +1        0 ns  10 ps" 
"4: time +I0(1)    0 ns  10 ps" 
"5: time +I(1)     0 ns  375 ps" 
"6: time +J0(-1,1)  0 ns  10 ps" 
"8: time +J0(-1,i)  0 ns  307 ps" 
"9: time +J(-1,1)   0 ns  371 ps" 
"10: time +K0(-1,i) 25 ns  25250 ps"
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0" 
```

```
0: time ;1!=0     0 ns  11 ps
1: time +(1!=0)   105 ns  105000 ps
2: time +(x!=y++) 127 ns  127000 ps
3: time +1        0 ns  12 ps
4: time +I0(1)    0 ns  11 ps
5: time +I(1)     4 ns  4031 ps
6: time +J0(-1,1)  111 ns  111000 ps
8: time +J0(-1,i)  114 ns  114000 ps
9: time +J(-1,1)   115 ns  115000 ps
10: time +K0(-1,i) 171 ns  171000 ps
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
```

```
0: time ;1!=0     0 ns  10 ps
1: time +(1!=0)   76 ns  75500 ps
2: time +(x!=y++) 80 ns  80000 ps
3: time +1        0 ns  10 ps
4: time +I0(1)    0 ns  10 ps
5: time +I(1)     4 ns  4281 ps
6: time +J0(-1,1)  83 ns  82500 ps
8: time +J0(-1,i)  87 ns  87000 ps
9: time +J(-1,1)   91 ns  91000 ps
10: time +K0(-1,i) 171 ns  171000 ps
nodejs v0.12.7
```

The code to produce this results is at https://www.av8n.com/computer/js-timing-1.js

Some observations:
* The benchmark code that was suggested on this tracker yesterday will never give reliable results, because the timing might be dominated by the loop overhead.  This problem can be *partially* mitigated by unrolling some of the code, and by playing games to confuse the javascript optimizer.
* The results will be wildly sensitive to what the javascript compiler feels like optimizing.
  * Sometimes sticking in a function call makes the code less optimizable.
  * Sometimes sticking in a function call makes the code more optimizable.

You can see that in firefox (line 9) the function call (including a comparison and increment) is dramatically **faster** than the simple inline comparison and increment (line 2).  This is diametrically opposite to some of the claims that were made yesterday.  Meanwhile, in nodejs and in chrome, the function call is slower, but only 10% slower ... not 13,900% slower.

* I emphatically do not claim that these numbers are sufficient to decide what to optimize and what not to optimize.  The main point of these numbers is to show that the numbers are wildly sensitive to details.  It would be unwise to decide based on these numbers.  The second point is that it would be 100 times more unwise to decide based on less-careful measurements, and even more unwise to decide based on guessing.
* As my smart friend suggested, the best approach is to write decent code that does the Right Thing, and then ***profile it*** under real-world conditions.  That will reveal what really needs optimizing.

**Comment by hartsantler** [comment] 2015-09-16 04:21
https://www.av8n.com/computer/js-timing-1.js

tried to look at the source from the link you gave above, but getting this error.
```bash
www.av8n.com uses an invalid security certificate. 
The certificate is not trusted because the issuer certificate is unknown. 
(Error code: sec_error_unknown_issuer)

**Comment by kovidgoyal** [comment] 2015-09-16 04:28
I suggest you pick some real world code, that makes significant use of the == operator, write two versions of it, and compare. Micro benchmarks, as you have found, are pretty meaningless. 

For instance, when I was trying to get ```if``` to behave as in python (i.e. return False for empty containers)
I found that the code I was working on at the time slowed down by 700% in code. And I dont recall the exact number but it was greater than 100% for compiling the RS compiler itself. 

An easy way to test this is edit src/output.pyj look around line 2000 for the function that outputs the '==' operator. Change it to call a rich comparator function instead, say _$rapyd$_equals when an environment variable is set. (Use process.environ to access environment variables in Node).
You will find the definition of _$rapyd$_equals in baselib-containers.pyj

Note that this is all with reference to my fork.

Now build the  compiler with

./build

And now compile some real world code with it (with the env var set and unset) and benchmark.

**Comment by kovidgoyal** [comment] 2015-09-16 04:29
Also important to note that if your real world code uses imports, you will need to delete all *.pyj-cached files when changing the environment variable.

**Comment by kovidgoyal** [comment] 2015-09-16 05:12
Just throwing this out there, it should be possible (and relatively easy to implement), to have compiler directives that optionally turn on operator overloading for the current module. It would work something like python's from __future__ import statement. So at the top of the .pyj file if you have

from __pycompat__ import operator_overloading, rich_bool, etc

then the compiler would output appropriate JS for just that module. Replacing ``==`` with ``equals()``, ``if expr`` with ``if rich_bool(expr)`` and so on.

So now the developer can choose whatever tradeoff she likes at the module level. That should put this debate to bed once and for all.

**Comment by JohnDenker** [comment] 2015-09-16 13:26
> from pycompat import rich_bool

I reeeally like that idea!  
Let's take a couple small steps further down the same road:
* To avoid undue conflicts with existing user code, it might be better to call it _Operator_EQ(a,b) rather than equals(a,b)
* It would be nice to also define __Operator_EQ (with an extra leading "_") as a wrapper for the above.  The compiler emits the wrapped version, for reasons discussed below.
* Those who want to optimize ***selected*** snippets of code can postprocess the compiler output.  For example, in some ***selected*** time-critical snippet where "===" is known to generate the correct result, one could do:
```
compiler  |  cpp -P -D'__Operator_EQ(a,b)=(a)===(b)'   >  final_result.js
```
For example:
```
echo '__Operator_EQ(1+2,3)' | cpp -P -D'__Operator_EQ(a,b)=(a)===(b)' 
(1+2)===(3)
```
Fancier optimizers could handle the easy cases inline, and then call the unwrapped _Operator_EQ(,) function to handle the remaining cases.

* If I were doing it, I would make rich_bool the default.  Anybody who needs the other behavior, in appropriately ***selected*** situations, is welcome to ask for it:
```
    from optimization import quick_and_dirty_bool
```

There is an important distinction between good optimization and bad optimization.  Certain inner loops are well worth optimizing ... but otherwise the vast, vast majority of the code is not worth optimizing.  Really not.  Remember Knuth's dictum:  ***Premature optimization is the root of all evil.***

**Comment by kovidgoyal** [comment] 2015-09-16 13:34
The compiler would obviously use _$rapyd$_equals not equals(). As for turning it off selectively, one just needs to use verbatim JS, like this v'a == b'

The problem, and the reason why I haven't bothered with this so far (though it has been in my mind for a while), is what to do about equality in contexts other than using the == operator. For example ``[].index`` or the ``in`` operator. Currently those all use JS === so are consistent. However, if the meaning of == changes from module to module what happens to those operations? The result of doing ``has_b = a in b`` will then be different from doing ``for x in a: if a == b: has_b = True``

**Comment by atsepkov** [comment] 2016-08-31 06:30
duplicate of #93

**Closed by atsepkov** 2016-08-31 06:30 UTC
